import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/components/navigation/NavBar'
import Footer from '@/components/navigation/Footer'
import { archivo } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={archivo.className}>
        <NavBar />

        {children}
        <Footer />
      </body>
    </html>
  )
}
