import type { Metadata } from 'next'
import { Archivo } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navigation/NavBar'
import Footer from '@/components/navigation/Footer'

const archivo = Archivo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={archivo.className}>
        <div className='mb-[62.2px]'>
          <NavBar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
